---
title: "Conclusion"
categories: Conclusion
author:
  - name: Alice Marin
    url: {}
date: 04-16-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

According to the different article we can observe that animal behaviours have a lot of impact on different factors.


Some animals can predict earthquakes. Chicks can insure their welfare and also give alert in case of imminent danger thanks to their cry. The presence of humans and their buildings has a huge impact on animal behaviours. Cats have the capacity to communicate with their eyes when communicating with their masters or others of their own specie. Climate change also has a lot of  impact on migration and birth from different species. Wild birds help with the well-being of animals in captivity. The choice of flowers for honey bees and bumblebees are different in relation to their current needs. Ants ingest their own acid for their welfare. Pinker flamingos are aggressive towards their own kind when they aren’t looking for food elsewhere.  Many factors can encourage fights between individuals of the same specie or even between species.


But a lot of questions remain unsolved. Why do animals have such behaviours? Can they have a big impact on our future? What other unknown behaviour could animals have?


# Bibliography

-	[https://www.sciencedaily.com/releases/2020/07/200706101837.htm] (Article 1)
-	[https://www.sciencedaily.com/releases/2020/06/200609190730.htm] (Article 2)
-	[https://www.sciencedaily.com/releases/2020/06/200622133020.htm] (Article 3)
-	[https://www.sciencedaily.com/releases/2020/10/201007123031.htm] (Article 4)
-	[https://www.sciencedaily.com/releases/2020/11/201105183834.htm] (Article 5)
-	[https://www.sciencedaily.com/releases/2021/02/210205104233.htm] (Article 6)
-	[https://www.sciencedaily.com/releases/2021/02/210210091131.htm] (Article 7)
-	[https://www.sciencedaily.com/releases/2020/11/201103104730.htm] (Article 8)
-	[https://www.sciencedaily.com/releases/2020/06/200607195010.htm] (Article 9)
-	[https://www.sciencedaily.com/releases/2020/11/201110133202.htm] (Article 10)

