---
title: "Introduction"
categories: Introduction
author:
  - name: Alice Marin
    url: {}
date: 04-16-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Firstly Ethology is the scientific study of animal behaviours as well as human behaviours in different condition ( for example in wild, an experimental environment, in captivity, … ). This study focuses on the scientific methods of observation and quantification of animal behaviours. One of the pioneers of ethology is Charles Darwin nominated for showing that the choice of a sexual partner in the animal kingdom is random, confirms the theory of natural selection. But there are many other pioneers of ethology such as Konrad Lorenz or Nikolaas Tinbergen. There are three big question in ethology: What are the roots of the behaviour? What is its impact in terms of survival ? How was it set up during the life of the individual and the evolution of the species? Currently there are a scientific training to become an ethologist .


Secondly, why did I chose this topic? this theme has always fascinated me because it help to understand animals. In my opinion, each living being has a consciousness that allows it to survive, grow and reproduce on this earth full of danger. If we learn to better understand animal behaviours, then we will better understand nature. I think that all species are linked together and also with us. Our future on earth is bound to the different species that make it up and our relation with animals will get better the more we understand each other . 


Thirdly what are the impacts of ethology? Ethology has allowed us to improve the conditions in which we keep species in captivity, as well as to better protect wild species. It has also helped us with specie introductions and the overall well-being of animals. 


Finally I will present several articles to give different examples of animal behaviours in relation to different situations regarding for instance their capacity adaptation in a new environment or also in their influence on our society. Thanks to these 10 articles, I will make you discover a part of ethology...


