---
title: "My English Activity Log : MEAL"
author:
  - name: "Alice Marin" 
date: "`r Sys.Date()`"
categories:
  - "English for Science"
  - "M.E.A.L."
output: distill::distill_article
---
per month:

* September:

  * I joined 'Wallangues', I try do all day
  * I joined 'speaky', I speak with native nearly all day.
  * I downloaded the 'BBC News' on my computer.I've started reading the news each monday
  * I watched first season of Alex Rider and Death Comes to Pemberley (English with French subtitles). 
  * I watched littles in video in English on youtube.

* October:

  * I watched the news for the bbc
  * I created my frist article on my blog
  
* November:

  * I created my second article on my blog
  * I watched a movie: Into the Wood, it is a musical comedy
  * I began to read book "Rose" nightly in English.
  * I trained on Quizlet (vocabulary) myself
  * I followed English remedial courses
  * I created my third article and my fourth article on my blog
  
* December

  * I watched second season of His Dark Materials (English with French subtiles)
  * I speaked with my cousins in English
  * I continued to read my book "Rose" every night before sleeping.
  * I took almost all remediation courses
  
* January
  
  * I studied for English exam
  * I read a lot of manga online in English
  * I continued to read my book "Rose"
  
* February

  




